[build]
  publish = "dist"
  command = "chmod +x netlify-build.sh && ./netlify-build.sh"

[build.environment]
  NODE_VERSION = "16.14.0"
  NPM_VERSION = "8.19.4"
  CI = "false"
  
  # Disable npm config that might cause issues
  NPM_CONFIG_UPDATE_NOTIFIER = "false"
  NPM_CONFIG_FUND = "false"
  NPM_CONFIG_AUDIT = "false"
  NPM_CONFIG_LOGLEVEL = "warn"
  
  # Disable Next.js telemetry
  NEXT_TELEMETRY_DISABLED = "1"

[[redirects]]
  from = "/api/*"
  to = "https://podcast-production-9a44.up.railway.app/api/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/ws/*"
  to = "https://podcast-production-9a44.up.railway.app/ws/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
