# This file tells Netlify how to build and serve your site

[build]
  # Base directory for the build
  base = "client"
  # Directory containing the built files
  publish = "dist"
  # Command to build the site
  command = "chmod +x netlify-build.sh && ./netlify-build.sh"

[build.environment]
  # Set Node.js version - must match .nvmrc
  NODE_VERSION = "16.14.0"
  # Set npm version
  NPM_VERSION = "8.19.4"
  # Set environment to production
  NODE_ENV = "production"
  # Disable CI to prevent build issues
  CI = "false"
  # Disable package-lock generation during install
  NPM_CONFIG_PACKAGE_LOCK = "false"
  # Disable npm update notifier
  NPM_CONFIG_UPDATE_NOTIFIER = "false"
  # Set npm cache directory
  NPM_CONFIG_CACHE = "/opt/build/.npm"
  # Enable npm cache
  NPM_CONFIG_CACHE_MIN = "9999999"
  # Disable npm fund messages
  NPM_CONFIG_FUND = "false"
  # Disable npm audit
  NPM_CONFIG_AUDIT = "false"
  # Set npm log level
  NPM_CONFIG_LOGLEVEL = "warn"
  # Disable telemetry
  NEXT_TELEMETRY_DISABLED = "1"
  # Disable package-lock.json
  NPM_CONFIG_PACKAGE_LOCK = "false"

# Production context settings
[context.production]
  command = "chmod +x netlify-build.sh && ./netlify-build.sh"
  [context.production.environment]
    NODE_ENV = "production"
    NODE_OPTIONS = "--max_old_space_size=1024"

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval'; style-src 'self' 'unsafe-inline'; img-src 'self' data: https:; font-src 'self' data:; connect-src 'self' https://podcast-production-9a44.up.railway.app;"

# API redirects
[[redirects]]
  from = "/api/*"
  to = "https://podcast-production-9a44.up.railway.app/api/:splat"
  status = 200
  force = true
  headers = { Access-Control-Allow-Origin = "*" }

# WebSocket redirects
[[redirects]]
  from = "/ws/*"
  to = "https://podcast-production-9a44.up.railway.app/ws/:splat"
  status = 200
  force = true
  headers = { Access-Control-Allow-Origin = "*" }

# SPA fallback
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Cache optimization plugin
[[plugins]]
  package = "@netlify/plugin-cache"

# Lighthouse plugin for performance monitoring
[[plugins]]
  package = "@netlify/plugin-lighthouse"
  [plugins.inputs.thresholds]
    performance = 0.8
    accessibility = 0.9
    best-practices = 0.9
    seo = 0.9
