[build]
  base = "."
  publish = "client/dist"
  command = "npm run netlify-build"

[build.environment]
  NODE_ENV = "production"

[[redirects]]
  from = "/api/*"
  to = "https://podcast-production-9a44.up.railway.app/api/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/ws/*"
  to = "https://podcast-production-9a44.up.railway.app/ws/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[dev]
  framework = "#custom"
  command = "npm start"
  targetPort = 3000
  port = 8888
  publish = "dist"
  autoLaunch = false
