# Netlify Configuration - Using Custom Build Script

[build]
  base = "client"
  publish = "dist"
  command = "chmod +x netlify-build.sh && ./netlify-build.sh"

[build.environment]
  NODE_VERSION = "16.14.0"
  NPM_VERSION = "8.19.4"
  NODE_ENV = "production"
  CI = "false"
  
  # Disable npm config that might cause issues
  NPM_CONFIG_UPDATE_NOTIFIER = "false"
  NPM_CONFIG_FUND = "false"
  NPM_CONFIG_AUDIT = "false"
  NPM_CONFIG_LOGLEVEL = "warn"
  
  # Disable Next.js telemetry
  NEXT_TELEMETRY_DISABLED = "1"

# Production context settings
[context.production]
  command = "chmod +x netlify-build.sh && ./netlify-build.sh"
  [context.production.environment]
    NODE_ENV = "production"
    NODE_OPTIONS = "--max_old_space_size=1024"

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval'; style-src 'self' 'unsafe-inline'; img-src 'self' data: https:; font-src 'self' data:; connect-src 'self' https://podcast-production-9a44.up.railway.app;"

# API redirects
[[redirects]]
  from = "/api/*"
  to = "https://podcast-production-9a44.up.railway.app/api/:splat"
  status = 200
  force = true
  headers = { Access-Control-Allow-Origin = "*" }

# WebSocket redirects
[[redirects]]
  from = "/ws/*"
  to = "https://podcast-production-9a44.up.railway.app/ws/:splat"
  status = 200
  force = true
  headers = { Access-Control-Allow-Origin = "*" }

# SPA fallback
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Cache optimization plugin
[[plugins]]
  package = "@netlify/plugin-cache"

# Lighthouse plugin for performance monitoring
[[plugins]]
  package = "@netlify/plugin-lighthouse"
  [plugins.inputs.thresholds]
    performance = 0.8
    accessibility = 0.9
    best-practices = 0.9
    seo = 0.9
