[build]
  base = "."
  publish = "client/dist"
  command = "npm run netlify-build"

[build.environment]
  NODE_VERSION = "16.14.0"
  NODE_ENV = "production"
  CI = false

[[redirects]]
  from = "/api/*"
  to = "https://podcast-production-9a44.up.railway.app/api/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/ws/*"
  to = "https://podcast-production-9a44.up.railway.app/ws/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
